version: '3.1'

services:
  webserver2:
    image: "nginx"
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
